"""Deterministic investor-demo seeding and reset.

Produces ONE repeatable, self-contained demonstration of the whole Petabyte loop —
seller onboarding, verified supply, buyer booking, explainable routing, job
lifecycle, settlement, earnings, and an admin audit trail — using only the real,
tested code paths (register / login / register_specs / prove / heartbeat / launch /
jobs). Nothing here weakens auth, isolation, or the money path.

HONESTY RULES (enforced by demo_test.py):
  * Every seeded entity is stamped is_demo=True and is reported separately from real
    data by /metrics/overview; the UI badges it "Demo data".
  * The demo agent NEVER executes buyer code. It is a legitimate node that holds its
    Ed25519 device key and signs results, but the result body is a clearly-labelled
    simulated string. Real execution still requires the real agent + Docker.
  * No fabricated partnerships, users-as-traction, or "production ready" claims.

Usage:
    python demo.py seed     # wipe + seed the configured DATABASE_URL, print accounts
    python demo.py reset    # same as seed (idempotent: full wipe then seed)
    python demo.py info     # print demo accounts + URLs without reseeding
"""
import base64
import json
import os
import sys
import time
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

DEMO_PASSWORD = "demo-Petabyte-2026!"      # fixed so the demo is repeatable
DEMO_PREFIX = "demo_"


def _sign(key, proof: dict) -> str:
    msg = json.dumps(proof, sort_keys=True, separators=(",", ":")).encode()
    return base64.b64encode(key.sign(msg)).decode()


# --- the demo supply: varied, realistic, honestly labelled -------------------
# region/country + the source IP that GEOIP_STUB maps to that country, so region
# verification is exercised for real rather than asserted.
DEMO_SELLERS = [
    {"user": "aurora_labs", "gpu": "H100", "vram": 80, "cpu": 32, "ram": 128,
     "price": 2.40, "units": 3, "region": "eu-west", "country": "DE",
     "ip": "10.1.1.1", "benchmark": 2380.0},
    {"user": "vega_compute", "gpu": "A100", "vram": 80, "cpu": 24, "ram": 96,
     "price": 1.55, "units": 4, "region": "us-east", "country": "US",
     "ip": "10.3.3.3", "benchmark": 1520.0},
    {"user": "nimbus_rigs", "gpu": "RTX 4090", "vram": 24, "cpu": 16, "ram": 64,
     "price": 0.62, "units": 6, "region": "us-west", "country": "US",
     "ip": "10.3.3.3", "benchmark": 900.0},
    {"user": "sirocco_gpu", "gpu": "L40", "vram": 48, "cpu": 16, "ram": 64,
     "price": 1.10, "units": 2, "region": "me-central", "country": "SA",
     "ip": "10.4.4.4", "benchmark": None},   # attested but not benchmarked yet
    {"user": "helios_secure", "gpu": "H100", "vram": 80, "cpu": 32, "ram": 128,
     "price": 3.20, "units": 2, "region": "eu-west", "country": "DE",
     "ip": "10.1.1.1", "benchmark": 2410.0, "confidential": True},
]

DEMO_BUYERS = [
    {"user": "northwind_ai", "deposit": 500.0},
    {"user": "delta_research", "deposit": 300.0},
    {"user": "quant_forge", "deposit": 250.0},
]

# Jobs to run: (buyer, template, hours, outcome). outcome drives the demo narrative:
#   completed -> settles (GMV, earnings, platform revenue)
#   running   -> left in-flight to show a live state
#   failed    -> reports failure -> booking refunded (reliability story)
DEMO_JOBS = [
    # region hints spread the demand across distinct sellers so the settlement story
    # shows a real marketplace, not one node winning everything on price.
    {"buyer": "northwind_ai", "template": "vllm", "hours": 2, "region": "eu-west",
     "outcome": "completed"},
    {"buyer": "northwind_ai", "template": "ollama", "hours": 1, "region": "us-west",
     "outcome": "completed"},
    {"buyer": "delta_research", "template": "comfyui", "hours": 3, "region": "us-east",
     "outcome": "completed"},
    {"buyer": "delta_research", "template": "jupyter", "hours": 1, "region": "eu-west",
     "outcome": "running"},
    {"buyer": "quant_forge", "template": "pytorch", "hours": 2, "region": "me-central",
     "outcome": "completed"},
    {"buyer": "quant_forge", "template": "vllm", "hours": 1, "region": "us-west",
     "outcome": "failed"},
]

SIMULATED_RESULT = ("SIMULATED — Petabyte investor demo. No buyer code was executed; "
                    "this output is generated by the demo harness to exercise the "
                    "settlement path end to end.")


class DemoError(RuntimeError):
    pass


def _post(client, path, **kw):
    return client.post(path, **kw)


def _login(client, user):
    r = client.post("/login", data={"username": user, "password": DEMO_PASSWORD})
    if r.status_code != 200:
        raise DemoError(f"login failed for {user}: {r.status_code} {r.text[:200]}")
    return {"Authorization": f"Bearer {r.json()['access_token']}"}


def wipe(dbmod):
    """Drop and recreate the whole schema. Destructive by design — the demo DB is
    disposable. Refuses to run against a URL that looks like production."""
    if os.getenv("ENVIRONMENT", "development").lower() == "production":
        raise DemoError("refusing to wipe: ENVIRONMENT=production")
    if dbmod.engine.dialect.name.startswith("postgres"):
        with dbmod.engine.begin() as c:
            c.exec_driver_sql("DROP SCHEMA public CASCADE; CREATE SCHEMA public;")
    else:
        # sqlite: drop every table
        dbmod.Base.metadata.drop_all(bind=dbmod.engine)
    dbmod.init_db()


def _stamp_demo(dbmod):
    """Mark every seeded row is_demo=True in one place, keyed off the username
    prefix. Done directly on the DB because is_demo is an internal integrity flag,
    never a client-settable field (a public 'make me demo' toggle would be abusable)."""
    s = dbmod.SessionLocal()
    try:
        demo_user_ids = [u.id for u in s.query(dbmod.User).filter(
            dbmod.User.username.like(f"{DEMO_PREFIX}%")).all()]
        for u in s.query(dbmod.User).filter(dbmod.User.id.in_(demo_user_ids)).all():
            u.is_demo = True
            s.add(u)
        for sp in s.query(dbmod.SellerSpec).filter(
                dbmod.SellerSpec.user_id.in_(demo_user_ids)).all():
            sp.is_demo = True
            s.add(sp)
        for b in s.query(dbmod.Booking).filter(
                dbmod.Booking.buyer_id.in_(demo_user_ids)).all():
            b.is_demo = True
            s.add(b)
        s.commit()
    finally:
        s.close()


def seed(client, dbmod):
    """Seed the demo. `client` is a TestClient or httpx.Client bound to the app.
    Returns a summary dict (accounts, counts) for the operator to print."""
    node_keys = {}          # username -> (Ed25519 key, spec_id, api_key)

    # --- sellers: onboard, attest, come online, benchmark -------------------
    for sd in DEMO_SELLERS:
        u = DEMO_PREFIX + sd["user"]
        client.post("/register_user", json={"username": u, "password": DEMO_PASSWORD})
        h = _login(client, u)
        client.post("/change_role", headers=h, json={"role": "seller"})
        body = {"cpu": sd["cpu"], "ram": sd["ram"], "duration": 168,
                "price_per_hour": sd["price"], "provider": sd["user"],
                "gpu_model": sd["gpu"], "gpu_count": 1, "vram_gb": sd["vram"],
                "units": sd["units"], "region": sd["region"], "country": sd["country"]}
        r = client.post("/register_specs", headers=h, json=body)
        if r.status_code != 200:
            raise DemoError(f"register_specs failed for {u}: {r.status_code} {r.text[:200]}")
        spec_id = r.json()["spec_id"]

        key = Ed25519PrivateKey.generate()
        pub = base64.b64encode(key.public_key().public_bytes_raw()).decode()
        att = {"cpu": sd["cpu"], "ram": sd["ram"], "gpu_model": sd["gpu"],
               "nonce": f"demo-{sd['user']}", "ts": int(time.time())}
        client.post("/prove", headers=h, json={"spec_id": spec_id, "attestation": att,
                                               "signature": _sign(key, att), "pubkey": pub})
        api_key = client.post("/create_api_key", headers=h).json()["api_key"]
        # region verification: heartbeat carries the node IP GEOIP_STUB maps to country
        client.post("/heartbeat", headers={"X-API-KEY": api_key, "X-Forwarded-For": sd["ip"]},
                    json={"spec_id": spec_id})

        if sd.get("confidential"):
            # confidential-computing PILOT: exercises the (stub) TEE verifier so the
            # node carries the CC flag. Explicitly not vendor hardware attestation.
            root = os.getenv("TEE_TRUSTED_ROOT")
            allow = (os.getenv("TEE_MEASUREMENT_ALLOWLIST", "").split(",") or [""])[0]
            if root and allow:
                nonce = client.post("/attestation/challenge", headers=h,
                                    json={"spec_id": spec_id}).json().get("nonce")
                if nonce:
                    vsk_raw = base64.b64decode(os.environ["_DEMO_VENDOR_SK"])
                    from cryptography.hazmat.primitives.asymmetric.ed25519 import (
                        Ed25519PrivateKey as _SK)
                    vsk = _SK.from_private_bytes(vsk_raw)
                    rep = {"nonce": nonce, "measurement": allow,
                           "vendor": "nvidia-h100-cc", "ts": int(time.time())}
                    client.post("/prove_tee", headers=h,
                                json={"spec_id": spec_id, "report": rep,
                                      "signature": _sign(vsk, rep)})

        if sd.get("benchmark"):
            client.post("/benchmark", headers=h, json={"spec_id": spec_id})
            bjob = client.get("/jobs/next", headers={"X-API-KEY": api_key}).json()
            bph = {"task_id": bjob["task_id"], "output_hash": "demo-bench",
                   "ts": int(time.time())}
            client.post("/jobs/benchmark_result", headers={"X-API-KEY": api_key},
                        json={"spec_id": spec_id, "tokens_sec": sd["benchmark"],
                              "meta": {"harness": "demo", "model": "demo-llm"},
                              "proof": bph, "signature": _sign(key, bph)})
        node_keys[u] = (key, spec_id, api_key)

    # --- buyers: fund wallets ----------------------------------------------
    for bd in DEMO_BUYERS:
        u = DEMO_PREFIX + bd["user"]
        client.post("/register_user", json={"username": u, "password": DEMO_PASSWORD})
        bh = _login(client, u)
        client.post("/deposit", headers=bh, json={"amount": bd["deposit"]})

    # --- jobs: launch (records routing), then the demo agent finishes them ---
    completed = running = failed = 0
    for jd in DEMO_JOBS:
        bu = DEMO_PREFIX + jd["buyer"]
        bh = _login(client, bu)
        launch_body = {"template": jd["template"], "hours": jd["hours"]}
        if jd.get("region"):
            launch_body["region"] = jd["region"]
        launch = client.post("/launch", headers=bh, json=launch_body)
        if launch.status_code != 200:
            # not enough matching supply for this template right now — skip, don't fabricate
            continue
        lr = launch.json()
        task_id = lr["task_id"]
        # find the node that got the task (its owner's key signs the result)
        owner_key = owner_api = None
        spec_id_for_task = None
        s = dbmod.SessionLocal()
        try:
            t = s.query(dbmod.Task).filter(dbmod.Task.id == task_id).first()
            spec_id_for_task = t.spec_id if t else None
        finally:
            s.close()
        for u, (k, sid, ak) in node_keys.items():
            if sid == spec_id_for_task:
                owner_key, owner_api = k, ak
                break
        if jd["outcome"] == "running" or not owner_key:
            running += 1
            continue
        # The demo agent returns a SIMULATED (non-executed) result for THIS task.
        # /jobs/result targets the task by id + node ownership, so no FIFO claim is
        # needed (claiming would mark a different queued task running and orphan it).
        status = "completed" if jd["outcome"] == "completed" else "failed"
        proof = {"task_id": task_id, "output_hash": f"demo-{task_id}", "ts": int(time.time())}
        res = client.post("/jobs/result", headers={"X-API-KEY": owner_api},
                          json={"task_id": task_id,
                                "result": SIMULATED_RESULT if status == "completed" else None,
                                "status": status, "proof": proof,
                                "signature": _sign(owner_key, proof)})
        if res.status_code == 200 and status == "completed":
            completed += 1
        elif status == "failed":
            failed += 1

    _stamp_demo(dbmod)

    # summary
    s = dbmod.SessionLocal()
    try:
        n_specs = s.query(dbmod.SellerSpec).filter(dbmod.SellerSpec.is_demo == True).count()  # noqa: E712
        n_users = s.query(dbmod.User).filter(dbmod.User.is_demo == True).count()  # noqa: E712
        n_bookings = s.query(dbmod.Booking).filter(dbmod.Booking.is_demo == True).count()  # noqa: E712
    finally:
        s.close()
    return {
        "sellers": [DEMO_PREFIX + s["user"] for s in DEMO_SELLERS],
        "buyers": [DEMO_PREFIX + b["user"] for b in DEMO_BUYERS],
        "password": DEMO_PASSWORD,
        "counts": {"demo_users": n_users, "demo_specs": n_specs,
                   "demo_bookings": n_bookings, "jobs_completed": completed,
                   "jobs_running": running, "jobs_failed": failed},
    }


def _print_info(summary):
    base = os.getenv("PUBLIC_BASE_URL") or os.getenv("DEMO_API_URL") or "http://127.0.0.1:8000"
    admin = os.getenv("ADMIN_USERS", "").split(",")[0].strip() or "(set ADMIN_USERS)"
    print("\n" + "=" * 68)
    print("  PETABYTE INVESTOR DEMO — ready.  (all data is labelled 'Demo data')")
    print("=" * 68)
    print(f"  Marketplace ....... {base}/marketplace")
    print(f"  Buyer dashboard ... {base}/app")
    print(f"  Metrics/ops ....... {base}/metrics")
    print(f"  Admin console ..... {base}/admin   (admin user: {admin})")
    print(f"  API reference ..... {base}/docs")
    print("-" * 68)
    print(f"  Demo password (all accounts): {summary['password']}")
    print(f"  Demo sellers: {', '.join(summary['sellers'])}")
    print(f"  Demo buyers:  {', '.join(summary['buyers'])}")
    c = summary["counts"]
    print(f"  Seeded: {c['demo_specs']} nodes, {c['demo_bookings']} bookings "
          f"({c['jobs_completed']} completed, {c['jobs_running']} running, "
          f"{c['jobs_failed']} failed)")
    print("=" * 68 + "\n")


def _bootstrap_env():
    """Set the stub/demo env the seeding needs, without clobbering an operator's
    explicit values. Keeps the demo runnable with zero paid credentials."""
    os.environ.setdefault("DATABASE_URL", "sqlite:///./demo.db")
    os.environ.setdefault("SECRET_KEY", "demo-secret-not-for-production")
    from cryptography.fernet import Fernet
    os.environ.setdefault("SERVER_PRIVATE_KEY", Fernet.generate_key().decode())
    os.environ.setdefault("PAYMENTS_MODE", "sandbox")
    os.environ.setdefault("PAYOUT_STUB", "true")
    os.environ.setdefault("NOTIFY_STUB", "true")
    os.environ.setdefault("S3_STUB", "true")
    os.environ.setdefault("GOOGLE_OAUTH_STUB", "true")
    os.environ.setdefault("WG_PUBLIC_KEY", "demoWGpublickeybase64==")
    os.environ.setdefault("WG_ENDPOINT", "vpn.demo.local")
    os.environ.setdefault("REAPER_DISABLED", "true")
    os.environ.setdefault("TRUSTED_PROXIES", "testclient,127.0.0.1,::1")
    os.environ.setdefault("GEOIP_STUB", json.dumps(
        {"10.1.1.1": "DE", "10.3.3.3": "US", "10.4.4.4": "SA"}))
    # confidential-computing pilot: a demo "vendor" key so the CC node can attest.
    vsk = Ed25519PrivateKey.generate()
    os.environ.setdefault("TEE_TRUSTED_ROOT",
                          base64.b64encode(vsk.public_key().public_bytes_raw()).decode())
    os.environ.setdefault("TEE_MEASUREMENT_ALLOWLIST", "mr_h100_cc_v1")
    os.environ["_DEMO_VENDOR_SK"] = base64.b64encode(vsk.private_bytes_raw()).decode()


def main(argv):
    cmd = argv[1] if len(argv) > 1 else "seed"
    _bootstrap_env()
    from fastapi.testclient import TestClient
    import db as dbmod
    import main as app_main
    if cmd in ("seed", "reset"):
        wipe(dbmod)
        client = TestClient(app_main.app)
        summary = seed(client, dbmod)
        _print_info(summary)
        return 0
    if cmd == "info":
        s = dbmod.SessionLocal()
        try:
            n = s.query(dbmod.SellerSpec).filter(dbmod.SellerSpec.is_demo == True).count()  # noqa: E712
            nb = s.query(dbmod.Booking).filter(dbmod.Booking.is_demo == True).count()  # noqa: E712
            jc = s.query(dbmod.Task).filter(dbmod.Task.status == "completed",
                                            dbmod.Task.task_type.in_(
                                                ("notebook", "template", "render",
                                                 "transcode", "stitch", "vm"))).count()
            jf = s.query(dbmod.Task).filter(dbmod.Task.status == "failed",
                                            dbmod.Task.task_type.in_(
                                                ("notebook", "template", "render",
                                                 "transcode", "stitch", "vm"))).count()
            jr = nb - jc - jf
        finally:
            s.close()
        _print_info({"sellers": [DEMO_PREFIX + x["user"] for x in DEMO_SELLERS],
                     "buyers": [DEMO_PREFIX + x["user"] for x in DEMO_BUYERS],
                     "password": DEMO_PASSWORD,
                     "counts": {"demo_specs": n, "demo_bookings": nb,
                                "jobs_completed": jc, "jobs_running": max(jr, 0),
                                "jobs_failed": jf}})
        return 0
    print(f"unknown command: {cmd}  (use: seed | reset | info)")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
