#!/usr/bin/env python3
"""Refresh the OFAC SDN digital-currency address list used by sanctions screening.

Downloads OFAC's PUBLIC Specially Designated Nationals list (no account, no API key) and extracts
every "Digital Currency Address - *" entry into a newline-delimited file that `sanctions.py`
screens USDC payouts against. Point OFAC_SDN_ADDRESSES_FILE at the output and run this from cron
(e.g. daily) to stay current — OFAC updates the list frequently.

    OFAC_SDN_ADDRESSES_FILE=/etc/lumaris/ofac_addresses.txt \
        python scripts/refresh_ofac_addresses.py

Exits non-zero on download/parse failure so cron records it. Writes atomically (temp + rename) so
a partial download never truncates the live list. Source: https://www.treasury.gov/ofac/downloads/sdn.xml
"""
from __future__ import annotations

import argparse
import os
import sys
import tempfile
import xml.etree.ElementTree as ET

SDN_XML_URL = os.getenv("OFAC_SDN_XML_URL", "https://www.treasury.gov/ofac/downloads/sdn.xml")


def _localname(tag: str) -> str:
    return tag.rsplit("}", 1)[-1]   # strip the XML namespace


def extract_addresses(xml_bytes: bytes) -> set:
    """Return the set of digital-currency addresses in an OFAC sdn.xml document.

    Legacy sdn.xml shape (namespaced):
      <sdnEntry> <idList> <id> <idType>Digital Currency Address - XBT</idType>
                                <idNumber>1abc…</idNumber> </id> … </idList> </sdnEntry>
    """
    root = ET.fromstring(xml_bytes)
    out = set()
    for el in root.iter():
        if _localname(el.tag) != "id":
            continue
        id_type = id_number = None
        for child in el:
            ln = _localname(child.tag)
            if ln == "idType":
                id_type = (child.text or "").strip()
            elif ln == "idNumber":
                id_number = (child.text or "").strip()
        if id_type and id_type.lower().startswith("digital currency address") and id_number:
            out.add(id_number)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description="Refresh the OFAC SDN crypto-address list.")
    ap.add_argument("--out", default=os.getenv("OFAC_SDN_ADDRESSES_FILE"),
                    help="output file (default: $OFAC_SDN_ADDRESSES_FILE)")
    ap.add_argument("--url", default=SDN_XML_URL, help="OFAC sdn.xml URL")
    args = ap.parse_args()
    if not args.out:
        sys.stderr.write("no output path — set OFAC_SDN_ADDRESSES_FILE or pass --out\n")
        return 2

    try:
        import httpx
        resp = httpx.get(args.url, timeout=60, follow_redirects=True)
        resp.raise_for_status()
        addresses = extract_addresses(resp.content)
    except Exception as e:  # noqa: BLE001
        sys.stderr.write(f"OFAC refresh FAILED: {e}\n")
        return 1

    if not addresses:
        sys.stderr.write("parsed 0 digital-currency addresses — refusing to overwrite the live "
                         "list with an empty file (format change or bad download?)\n")
        return 3

    header = ("# OFAC SDN digital-currency addresses — generated by "
              "scripts/refresh_ofac_addresses.py\n# source: " + args.url + "\n")
    body = "\n".join(sorted(addresses)) + "\n"
    out_dir = os.path.dirname(os.path.abspath(args.out)) or "."
    os.makedirs(out_dir, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=out_dir, prefix=".ofac-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(header + body)
        os.replace(tmp, args.out)   # atomic
    finally:
        if os.path.exists(tmp):
            os.remove(tmp)

    print(f"wrote {len(addresses)} OFAC digital-currency addresses -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
