"""baseline schema — the full current model as one Alembic migration

Adopting Alembic on a codebase whose schema was historically built by SQLAlchemy `create_all`
plus idempotent `_ensure_*` passes (init_db). This baseline reproduces EXACTLY that schema so
`alembic upgrade head` on an empty database yields the same schema `init_db()` builds — the two
are the SAME source (the models), so they cannot drift. Future schema changes get incremental,
autogenerated migrations stacked on top of this revision.

We delegate to `db.init_db()` (create_all + _ensure_columns + _ensure_check_constraints +
_ensure_indexes) rather than a hand-transcribed CREATE TABLE for all 54 tables, so the baseline
can never fall out of sync with the models. It is fully idempotent.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-16
"""

# revision identifiers, used by Alembic.
revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def _db():
    import os
    # Never trigger db's import-time init_db() as a side effect — this migration owns it.
    os.environ.setdefault("PETABYTE_SKIP_INIT_DB", "1")
    import db
    return db


def upgrade() -> None:
    # Build the complete current schema exactly as the runtime bootstrap does. Idempotent:
    # a partially-migrated or create_all-built DB is brought to head without error.
    _db().init_db()


def downgrade() -> None:
    # Drop on ALEMBIC'S OWN connection, not db.engine's separate pool: a prior revision's DDL
    # lock (released only at its transaction commit) must never deadlock these DROPs across
    # connections.
    from alembic import op
    _db().Base.metadata.drop_all(bind=op.get_bind())
