"""Update sellerspec  model

Revision ID: 1ad3c0c94975
Revises: effe95d6ce90
Create Date: 2025-06-29 21:20:28.026375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad3c0c94975'
down_revision: Union[str, Sequence[str], None] = 'effe95d6ce90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_specs_user_id'), 'specs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_specs_user_id'), table_name='specs')
    op.drop_column('specs', 'user_id')
    # ### end Alembic commands ###
