"""Update sellerspec  model

Revision ID: effe95d6ce90
Revises: b30c2b8d6b14
Create Date: 2025-06-29 21:17:36.087946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'effe95d6ce90'
down_revision: Union[str, Sequence[str], None] = 'b30c2b8d6b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specs', sa.Column('zk_proof', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specs', 'zk_proof')
    # ### end Alembic commands ###
